server:
  port: ${PORT:8081} # Usando porta 8081

spring:
  # Configuração do PostgreSQL
  datasource:
    url: ${DB_URL:jdbc:postgresql://server-cearabank.postgres.database.azure.com:5432/postgres}
    username: ${DB_USERNAME:postgres} 
    password: ${DB_PASSWORD:Unifametro@2026}
    driver-class-name: org.postgresql.Driver
  application:
     name: ceara-bank-transfer
  security:
     enabled: false
  
  # Configuração JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração do Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html 
  api-docs:
    path: /v3/api-docs

# --- ESTRUTURA RECOMENDADA PELO MAXO (USADA NO SERVICE) ---
microservicos:
  security:
    # URL completa do endpoint de validação no microserviço de segurança (8081)
    url-validacao-token: ${URL_VALIDACAO:http://localhost:8082/v1/seguranca/validarToken}