server:
  port: 8085 # Usando porta 8085

spring:
  # Configuração do PostgreSQL
  datasource:
    url: jdbc:postgresql://192.168.154.126:5432/cearabank_db
    username: postgres 
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
     name: ceara-bank-transfer
  security:
     enabled: false
  
  # Configuração JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração do Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html 
  api-docs:
    path: /v3/api-docs

# --- ESTRUTURA RECOMENDADA PELO MAXO (USADA NO SERVICE) ---
microservicos:
  security:
    # URL completa do endpoint de validação no microserviço de segurança (8081)
    url-validacao-token: http://localhost:8081/v1/seguranca/validarToken